/* Traditional Chinese (Hong Kong) copy. Keys are the exact English
   innerHTML of the element they translate. See i18n.js. */
window.ZH = Object.assign(window.ZH || {}, {
 "People": "人員",
 "Study": "課程",
 "Experience and Opportunities": "體驗與機會",
 "Admissions": "入學申請",
 "News and Events": "最新消息",
 "About": "關於我們",
 "Brand Guidelines ↗": "品牌指引 ↗",
 "Programme Leadership": "課程領導團隊",
 "Personal Academic Mentors": "個人學術導師",
 "Our Students": "我們的學生",
 "Undergraduate Studies Support Team": "本科課程支援團隊",
 "Programme Overview": "課程概覽",
 "Interdisciplinary Core Subjects": "跨學科核心科目",
 "Self-Determined Curriculum": "自訂課程",
 "Three Pathways": "三種修讀路徑",
 "Award Designation": "學位名銜",
 "Sample Study Plans": "修讀計劃示例",
 "One-on-One Mentorship": "一對一導師指導",
 "Guaranteed Hall Residence": "保證宿位",
 "Human Skills Development": "人文素養培育",
 "Global Exposure and Exchange": "環球視野與交流",
 "Internships and Work-Integrated Education": "實習與工作綜合教育",
 "JUPAS (JS3000)": "大學聯招（JS3000）",
 "Mainland JEE / Gaokao": "內地高考",
 "International Qualifications": "國際學歷",
 "Entrance Scholarships": "入學獎學金",
 "What's New": "最新消息",
 "Student-Led Forums": "學生主導論壇",
 "Information Sessions": "課程資訊講座",
 "Our Vision": "我們的願景",
 "Why Interdisciplinary Studies": "為何選擇跨學科",
 "Relation to Other PolyU Programmes": "與理大其他課程的關係",
 "Contact Us": "聯絡我們",
 "Skip to main content": "跳至主要內容",
 "2027 Entry · JUPAS JS3000": "2027 年入學 · 聯招 JS3000",
 "Open for Application": "現正接受申請",
 "Thirty places, recruited globally, with the highest entry score requirement of any programme at PolyU.": "三十個學額，面向全球招生，入學成績要求為理大之冠。",
 "Apply now": "立即申請",
 "Mentorship": "導師制度",
 "A professor of your own": "屬於你的教授",
 "Every BDSIS student is matched one-on-one with a Personal Academic Mentor: an accomplished professor in their field of interest, in some cases a member of the University's senior management.": "每位 BDSIS 學生均獲配對一位個人學術導師，一對一指導：導師為學生興趣領域中卓有成就的教授，部分更是大學高層管理成員。",
 "Meet the mentors": "認識導師團隊",
 "Curriculum": "課程設計",
 "Build a degree that does not exist yet": "建構一個尚未存在的學位",
 "Sixty credits of self-determined curriculum, drawn from any department across ten Faculties and Schools. Current students are combining Applied Mathematics with Finance, AI with Aviation, and Hospitality with Psychology.": "六十學分的自訂課程，科目可選自十個學院及學系的任何部門。現屆學生的組合包括：應用數學與金融、人工智能與航空、酒店管理與心理學。",
 "See how it works": "了解運作方式",
 "Leadership": "領導團隊",
 "Led by a social scientist and an engineer": "由社會科學家與工程師共同領導",
 "Prof. Daniel T.L. Shek, Chair Professor of Applied Social Sciences, and Prof. Alan P.T. Lau, Professor of Electrical and Electronic Engineering, who took his PhD at Stanford.": "應用社會科學講座教授石丹理教授，與電機及電子工程學系劉柏達教授（史丹福大學博士）。",
 "Programme leadership": "課程領導團隊",
 "Slide 1": "第 1 張",
 "Slide 2": "第 2 張",
 "Slide 3": "第 3 張",
 "Slide 4": "第 4 張",
 "Pause carousel": "暫停輪播",
 "Play carousel": "播放輪播",
 "Search this site": "搜尋本網站",
 "Share this page": "分享此頁",
 "Intranet": "內聯網",
 "Quick Access": "快速連結",
 "\"Nurturing future leaders to shape and sustain human-centric societies with rapidly evolving technology.\"": "「培育未來領袖，在科技急速演變的世代中，塑造並守護以人為本的社會。」",
 "The vision of the Bachelor's Degree Scheme in Interdisciplinary Studies": "跨學科組合學士課程的願景",
 "28 July 2026": "2026 年 7 月 28 日",
 "14 July 2026": "2026 年 7 月 14 日",
 "2 July 2026": "2026 年 7 月 2 日",
 "20 June 2026": "2026 年 6 月 20 日",
 "9 June 2026": "2026 年 6 月 9 日",
 "30 May 2026": "2026 年 5 月 30 日",
 "18 May 2026": "2026 年 5 月 18 日",
 "6 May 2026": "2026 年 5 月 6 日",
 "BDSIS Opens Applications for 2027 Entry with Thirty Places Under Global Recruitment": "BDSIS 開放 2027 年入學申請 全球招收三十名學生",
 "The scheme will admit thirty students for September 2027, recruiting through JUPAS, the Mainland JEE and international qualifications…": "本課程將於 2027 年 9 月招收三十名學生，招生途徑包括大學聯招、內地高考及國際學歷……",
 "Prof. Hongxia Yang Joins the Personal Academic Mentor Panel": "楊紅霞教授加入個人學術導師團隊",
 "The Associate Dean of the Faculty of Computational and Mathematical Sciences, formerly Head of Large Language Models at ByteDance US…": "計算機及數學科學學院副院長，曾任字節跳動美國大型語言模型主管……",
 "First Cohort Confirms Study Focuses Ahead of Schedule": "首屆學生提前確立修讀方向",
 "All nineteen students of the founding cohort have indicated a study focus by the end of Semester 1 of Year 1, ranging from Learning Science to Game Design…": "首屆十九名學生已於一年級上學期結束前確立修讀方向，涵蓋學習科學以至遊戲設計……",
 "Student-Led Forum Debates AI Companionship and Human Needs": "學生主導論壇探討人工智能陪伴與人類需求",
 "The CUS201 Reflections on Contemporary Issues forum brought students, staff and external stakeholders together to examine chatbot companionship…": "CUS201「當代議題反思」論壇匯聚學生、教職員及校外持份者，共同探討聊天機械人的陪伴角色……",
 "Prof. Kaye Chon Mentors Hospitality and Psychology Student Through Capstone Design": "田桂成教授指導酒店管理與心理學學生設計畢業專題",
 "The Dean of the School of Hotel and Tourism Management is supervising an interdisciplinary capstone on guest experience and wellbeing…": "酒店及旅遊業管理學院院長正指導一項關於賓客體驗與身心健康的跨學科畢業專題……",
 "Interdisciplinary Capstone Projects Pair Students with Industry Partners": "跨學科畢業專題與業界夥伴協作",
 "Fourth-year projects will be delivered with inter-sector partnership, addressing local, national and global issues of significance…": "四年級專題將以跨界別協作方式進行，探討本地、國家及全球的重要議題……",
 "Orientation Dinner Brings Senior University Management to the Founding Cohort": "迎新晚宴 大學高層與首屆學生共聚",
 "Students met the Dean of the College of Undergraduate Studies and members of senior management over dinner at the start of the academic year…": "學年伊始，學生於晚宴中與本科生院院長及大學高層管理成員會面……",
 "Human Skills Workshops Open to BDSIS Students with Enrolment Fee Waived": "人文素養工作坊向 BDSIS 學生開放並豁免報名費",
 "Courses and workshops offered by the Student Affairs Office are available to scheme students at no charge, unlike other undergraduate programmes…": "學生事務處開辦的課程及工作坊，本課程學生可免費參加，有別於其他本科課程……",
 "All news": "所有消息",
 "Two complementary dimensions": "兩個相輔相成的向度",
 "Technology advancement leads to a more interdisciplinary world with new and more complex challenges. Human needs, aspirations and the foundations of human society do not change at the same pace.": "科技進步令世界日益跨學科化，並帶來更新更複雜的挑戰。然而人類的需求、抱負以及社會構成的根基，並不會以同樣速度改變。",
 "Dimension one": "向度一",
 "Dimension two": "向度二",
 "Interdisciplinary knowledge, skills and mindsets": "跨學科的知識、技能與思維",
 "Future-ready students need both broad and specialised knowledge, and the capacity to think across the boundaries of disciplines. Self-learning matters more as the half-life of any single body of knowledge shortens.": "面向未來的學生既需要廣博亦需要專精的知識，並具備跨越學科邊界思考的能力。當任何單一知識體系的半衰期不斷縮短，自主學習便愈見重要。",
 "Deep understanding of human needs and society": "對人類需求與社會的深刻理解",
 "Places for 2027 entry, recruited globally": "2027 年入學學額，面向全球招生",
 "Personal Academic Mentor for every student, one-on-one": "每位學生配對一位個人學術導師，一對一指導",
 "Faculties and Schools to draw subjects from": "個學院及學系可供選修科目",
 "Credits of self-determined curriculum you design yourself": "學分的自訂課程，由你親自設計",
 "The curriculum": "課程結構",
 "One hundred and twenty credits minimum. Four interdisciplinary core subjects hold the scheme together; everything else you build.": "最低畢業要求為一百二十學分。四科跨學科核心科目貫穿整個課程，其餘部分由你自行建構。",
 "Interdisciplinary core": "跨學科核心",
 "Self-determined curriculum": "自訂課程",
 "General University Requirements": "大學通識要求",
 "Free electives": "自由選修",
 "18 credits": "18 學分",
 "27 credits": "27 學分",
 "9–12 credits": "9–12 學分",
 "Bars are drawn to scale against the 120-credit minimum. Work-Integrated Education is recorded as training credits and sits outside this total.": "圖表按一百二十學分的最低要求等比繪製。工作綜合教育以訓練學分計算，不計入此總數。",
 "CUS101 · Year 1": "CUS101 · 一年級",
 "CUS201/301 · Years 2–3": "CUS201/301 · 二至三年級",
 "CUS202 · Year 2": "CUS202 · 二年級",
 "CUS401 · Year 4": "CUS401 · 四年級",
 "Introduction to Interdisciplinary Studies": "跨學科研究導論",
 "Reflections on Contemporary Issues I &amp; II": "當代議題反思 I 及 II",
 "Interdisciplinary Research Methods": "跨學科研究方法",
 "Interdisciplinary Capstone": "跨學科畢業專題",
 "Three ways to build it": "三種建構方式",
 "Every self-determined curriculum is agreed in consultation with the programme director and your academic advisor.": "所有自訂課程均須與課程總監及學術顧問商議後確定。",
 "Pathway 01 · Solving world problems": "路徑 01 · 解決世界難題",
 "Start without a focus and work towards one": "先不設定方向，逐步聚焦",
 "Pathway 02 · Integrating known fields": "路徑 02 · 整合既有領域",
 "Start with a focus and build the study around it": "先確立方向，再圍繞它建構課程",
 "An integrated study of two or three existing subject disciplines, with subjects selected from those majors.": "整合兩至三個既有學科的綜合研習，科目選自相關主修。",
 "Pathway 03 · Strands": "路徑 03 · 主題範疇",
 "Choose from one to three strands": "從一至三個主題範疇中選擇",
 "Cultures and Societies · Sciences and Engineering · Health and Environment. Subjects are selected from the catalogue and categorised by strand.": "文化與社會 · 科學與工程 · 健康與環境。科目從科目目錄中選取，並按範疇分類。",
 "Two students, two degrees": "兩位學生，兩個學位",
 "Drawn from the current cohort of nineteen.": "取自現屆十九名學生。",
 "Hospitality &amp; Tourism": "酒店及旅遊",
 "Psychology": "心理學",
 "Artificial Intelligence": "人工智能",
 "Financial Technology": "金融科技",
 "Lyra": "Lyra",
 "Yiran": "Yiran",
 "Award: BSc (Hons) in Interdisciplinary Studies, with a focus on Hotel Management": "學位：跨學科研究理學士（榮譽），主修方向為酒店管理",
 "Award: BSc (Hons) in Interdisciplinary Studies, with a focus on Artificial Intelligence and Financial Technology": "學位：跨學科研究理學士（榮譽），主修方向為人工智能與金融科技",
 "What is different": "分別在哪裡",
 "BDSIS is an upgraded version of any PolyU undergraduate programme. This is what the upgrade consists of.": "BDSIS 是理大任何本科課程的升級版本。升級的內容如下。",
 "BDSIS": "BDSIS",
 "Other PolyU undergraduate programmes": "理大其他本科課程",
 "Hall residence": "宿舍住宿",
 "Not applicable": "不適用",
 "Top scholars and University senior management as one-on-one mentors, providing personalised coaching and in-depth mentorship": "頂尖學者及大學高層管理擔任一對一導師，提供個人化指導與深度啟導",
 "Guaranteed for the first two years of study": "首兩學年保證獲分配宿位",
 "Not guaranteed; prioritised by living district, home environment and contribution to campus and hall life": "不設保證；按居住地區、家庭環境及對校園與宿舍生活的貢獻排序",
 "Human skills courses and workshops": "人文素養課程及工作坊",
 "Enrolment fee waived": "豁免報名費",
 "Enrolment fee required": "須繳報名費",
 "Overseas trips, service learning, exchange, internships": "海外考察、服務學習、交流、實習",
 "Enhanced": "加強",
 "Standard": "標準",
 "Option to change": "轉換課程選項",
 "May switch back to another regular programme in Year 2, subject to approval": "可於二年級申請轉回一般課程，須經批准",
 "Three layers of advising": "三層指導架構",
 "Students confirm their focus by Semester 1 of Year 2, with support at three levels.": "學生須於二年級上學期前確立修讀方向，過程中獲三個層面的支援。",
 "Layer one": "第一層",
 "Layer two": "第二層",
 "Layer three": "第三層",
 "Personal Academic Mentor": "個人學術導師",
 "A renowned professor in the discipline of interest, one-on-one. Guidance on aspirations and pathway, disciplinary and interdisciplinary trends, and shared experience.": "由學生感興趣範疇中的知名教授一對一指導，就抱負與路徑、學科與跨學科趨勢提供意見，並分享經驗。",
 "Dean and Associate Dean": "院長與副院長",
 "Higher-level advice grounded in personal character and aspirations, with the ability to mobilise University-wide support.": "從個人特質與抱負出發提供更高層次的意見，並能調動全校資源支援。",
 "Undergraduate Studies Support": "本科課程支援團隊",
 "Administrative colleagues from the College who keep academic progression smooth, and review each study plan at the end of every semester.": "本科生院的行政同事確保學業進度順暢，並於每學期末檢視每份修讀計劃。",
 "BDSIS Student Intranet": "BDSIS 學生內聯網",
 "Study Plan Builder": "修讀計劃編製工具",
 "Subject Catalogue": "科目目錄",
 "Staff Intranet": "教職員內聯網",
 "Contact": "聯絡",
 "University": "大學",
 "Bachelor's Degree Scheme in Interdisciplinary Studies": "跨學科組合學士課程",
 "College of Undergraduate Studies": "本科生院",
 "The Hong Kong Polytechnic University": "香港理工大學",
 "Hung Hom, Kowloon, Hong Kong": "香港九龍紅磡",
 "Interdisciplinary Core": "跨學科核心",
 "Mainland JEE": "內地高考",
 "About PolyU": "關於理大",
 "Campus Map": "校園地圖",
 "PolyU A to Z": "理大 A 至 Z",
 "Privacy Policy Statement": "私隱政策聲明",
 "Terms of Use": "使用條款",
 "Accessibility": "無障礙瀏覽",
 "Sitemap": "網站地圖",
 "Copyright © 2026 The Hong Kong Polytechnic University. All Rights Reserved.": "版權所有 © 2026 香港理工大學",
 "Legal": "法律資訊",
 "Main": "主要導覽",
 "Featured": "精選內容",
 "Understand the world and its problems, and what interdisciplinarity means. Then choose a direction of study based on the problems you want to address. Develop a study plan. <strong>3 credits</strong>": "認識世界及其面對的問題，理解何謂跨學科。繼而按你希望處理的問題選定修讀方向，並制訂修讀計劃。<strong>3 學分</strong>",
 "Student-led forums in which local, national and global issues of significance are discussed with staff and external stakeholders. Students write a reflection. <strong>6 credits</strong>": "由學生主導的論壇，與教職員及校外持份者共同探討本地、國家及全球的重要議題，學生須撰寫反思報告。<strong>6 學分</strong>",
 "Research design, methodology and ethics for complex societal issues. Prepares students for self-directed study and for planning the capstone. <strong>3 credits</strong>": "針對複雜社會議題的研究設計、方法學與倫理，為學生的自主學習及畢業專題規劃作好準備。<strong>3 學分</strong>",
 "A project addressing a local, national, regional or global issue of significance, delivered with inter-sector partnership. Report plus reflection. <strong>6 credits</strong>": "以跨界別協作方式進行的專題研習，探討本地、國家、地區或全球的重要議題，須提交報告及反思。<strong>6 學分</strong>",
 "Resort management, event experience and wine studies alongside abnormal, cross-cultural and counselling psychology. Mentored by <strong>Prof. Kaye Chon</strong>, Dean of the School of Hotel and Tourism Management.": "修讀度假村管理、活動體驗及葡萄酒學，同時兼修變態心理學、跨文化心理學與輔導心理學。由酒店及旅遊業管理學院院長<strong>田桂成教授</strong>擔任導師。",
 "Machine learning, data mining and computer systems security alongside business valuation, international finance and e-payment. Mentored by <strong>Prof. Hongxia Yang</strong>, Associate Dean of the Faculty of Computational and Mathematical Sciences.": "修讀機器學習、數據探勘及電腦系統保安，同時兼修企業估值、國際金融與電子支付。由計算機及數學科學學院副院長<strong>楊紅霞教授</strong>擔任導師。",
 "Bachelor's Degree Scheme in Interdisciplinary Studies<br>\n          College of Undergraduate Studies<br>\n          The Hong Kong Polytechnic University<br>\n          Hung Hom, Kowloon, Hong Kong": "跨學科組合學士課程<br>\n          本科生院<br>\n          香港理工大學<br>\n          香港九龍紅磡",
 "<a href=\"#\">bdsis@polyu.edu.hk</a><br>\n          (852) 2766 0000": "<a href=\"#\">bdsis@polyu.edu.hk</a><br>\n          (852) 2766 0000",
 "3 credits": "3 學分",
 "6 credits": "6 學分",
 "Prof. Kaye Chon": "田桂成教授",
 "Prof. Hongxia Yang": "楊紅霞教授",
 "Home | Bachelor's Degree Scheme in Interdisciplinary Studies": "主頁 | 跨學科組合學士課程",
 "Logo": "標誌",
 "Banner": "橫幅",
 "Grid": "網格",
 "Typography": "字體",
 "Colour": "顏色",
 "Shape kit": "圖形組件",
 "Components": "元件",
 "Print": "印刷",
 "Themes": "主題",
 "Tokens": "設計變數",
 "Principles": "原則",
 "The logo": "標誌",
 "The institutional banner": "機構橫幅",
 "Navigation": "導覽",
 "Grid and spacing": "網格與間距",
 "The shape kit": "圖形組件",
 "Imagery": "圖像",
 "Print artifacts": "印刷物料",
 "Accessibility and motion": "無障礙與動效",
 "Do and don’t": "應做與不應做",
 "Do and don't": "應做與不應做",
 "Token reference": "設計變數總覽",
 "Designing the BDSIS website": "BDSIS 網站設計指引",
 "Designing the BDSIS Website | Brand Guidelines": "BDSIS 網站設計指引 | 品牌指引",
 "BDSIS Brand Guidelines · Web · Version 1.0 · August 2026": "BDSIS 品牌指引 · 網站 · 1.0 版 · 2026 年 8 月",
 "← Back to the site": "← 返回網站",
 "Two lockups": "兩款組合標誌",
 "Full colour and monocolor": "全彩與單色",
 "On dark grounds": "深色背景上的應用",
 "Combined with the University logo": "與大學標誌並用",
 "The mark alone": "單獨使用圖形",
 "Clear space": "留白範圍",
 "Minimum size": "最小尺寸",
 "The logo in print": "標誌的印刷應用",
 "Never": "絕不可",
 "Why the banner is white in every theme": "為何橫幅在所有主題中維持淺色",
 "Spacing scale": "間距級數",
 "Read this before you sign off a design": "設計定稿前必讀",
 "Weights": "字重",
 "Scale": "字級",
 "The scale, rendered": "字級實例",
 "Tracking": "字距",
 "Chinese": "中文",
 "PolyU corporate": "理大機構色",
 "The ground": "底色",
 "The BDSIS families": "BDSIS 色彩家族",
 "Family colours as text": "家族色作文字使用",
 "The families in Dark": "深色主題中的色彩家族",
 "Full specification": "完整規格",
 "Pantone": "Pantone",
 "Gradients in spot colour": "專色印刷的漸變處理",
 "Tangerine is the exception, and it is worth understanding why": "橘色是例外，值得理解箇中原因",
 "Assignment": "指派原則",
 "The one-corner rule": "單圓角規則",
 "Cell tiles": "色塊圖磚",
 "Buttons": "按鈕",
 "Section heading": "章節標題",
 "Sections": "章節",
 "News card": "消息卡片",
 "Statistics": "數字",
 "Pathway": "修讀路徑",
 "Student profile": "學生檔案",
 "Credit diagram": "學分圖表",
 "Comparison table": "比較表格",
 "Quick links": "快速連結",
 "Production defaults": "印製預設",
 "The artifact set": "物料清單",
 "Composition in print": "印刷版面構成",
 "Mockups": "模擬檔案",
 "Heading weight": "標題字重",
 "Text on a coloured field": "色塊上的文字",
 "Corners": "圓角",
 "Filling a shape": "圖形填色",
 "Line breaks and the fallback face": "斷行與替代字體",
 "Cards in a row": "同列卡片",
 "Light": "淺色",
 "Dark": "深色",
 "Dark Mono Gold": "深色單金",
 "The families, relit for Dark": "為深色主題重新調校的色彩家族",
 "Text on a family field": "家族色塊上的文字",
 "Space": "間距",
 "Corner and elevation": "圓角與陰影",
 "Layout": "版面",
 "Type": "字體",
 "The declaration": "變數宣告",
 "Four rules settle most questions.": "四項原則足以解答大部分疑問。",
 "Every BDSIS page opens with the same 100&nbsp;px white bar carrying four zones, in this order, left to right.": "每一個 BDSIS 頁面均以同一條 100&nbsp;px 高的淺色橫幅開始，由左至右依次載有四個區塊。",
 "The BDSIS mark is a 3×3 grid of quarter circles and one split square. The brand artwork extracts that construction into four primitives, and those four do every piece of graphic work on the site. There is no fifth shape, and no symbolism is attached to any of them: they are the mark's own geometry, reused.": "BDSIS 圖形由 3×3 網格構成，包含四分圓與一個沿對角線分割的方形。品牌圖檔將此構成提煉為四個基本圖形，網站上所有圖像工作皆由這四者承擔。並無第五種圖形，亦不賦予任何象徵意義：它們就是標誌本身的幾何，重新運用而已。",
 "Every specimen below is the real component, rendered from <code class=\"tok\">web.css</code>. Change the stylesheet and this page changes with it.": "以下每一個範例都是實際元件，由 <code class=\"tok\">web.css</code> 直接繪製。修改樣式表，本頁亦會隨之改變。",
 "The same system, on paper. Two things change: colour becomes CMYK, and the shape kit gets to bleed off the trim in a way it never does on screen.": "同一套系統，應用於紙本。兩點不同：色彩改為 CMYK，而圖形組件可以出血至裁切線外——這是螢幕上不會出現的做法。",
 "Each pair is rendered live, so the wrong version really is wrong on this page.": "每一組對照均為即時繪製，因此錯誤示範在本頁上確實是錯的。",
 "Three grounds, switched from the control at the bottom left of every page and stored per visitor. The switch sets <code class=\"tok\">data-theme</code> on <code class=\"tok\">&lt;html&gt;</code> and redefines tokens only, so anything written against the token set follows on its own.": "三種底色，可透過每頁左下角的控制項切換，並按訪客個別儲存。切換時會在 <code class=\"tok\">&lt;html&gt;</code> 上設定 <code class=\"tok\">data-theme</code>，並僅重新定義變數，因此任何依循變數撰寫的元件都會自動跟隨。",
 "Each token drawn at the value it actually holds. Everything else in <code class=\"tok\">web.css</code> is built from these.": "每個變數均以其實際數值繪製。<code class=\"tok\">web.css</code> 中其餘一切皆由此建構而成。",
 "<strong>The University furniture is not ours to redesign.</strong> The banner, the PolyU red block, the grey footer and the legal bar are shared across every PolyU site. Match them. Only the unit lockup on the left changes.": "<strong>大學的既定元素不由我們重新設計。</strong>橫幅、理大紅色塊、灰色頁尾及法律資訊列為所有理大網站共用，必須依樣採用。只有左方的單位標誌會有所不同。",
 "<strong>Two reds, two jobs.</strong> PolyU Red <code class=\"tok\">#A02337</code> belongs to the University and appears in exactly one place: the banner block behind the PolyU logo. BDSIS Red <code class=\"tok\">#AB0334</code> is ours, and carries our own buttons, links, end band and shape markers. Neither may stand in for the other.": "<strong>兩種紅，各司其職。</strong>理大紅 <code class=\"tok\">#A02337</code> 屬於大學，只出現於一處：橫幅中理大標誌背後的色塊。BDSIS 紅 <code class=\"tok\">#AB0334</code> 屬於我們，用於自家的按鈕、連結、結尾色帶及圖形標記。兩者不可互相替代。",
 "<strong>The wordmark is drawn as a mask, not baked into the artwork.</strong> One file per lockup serves black, white and gold, so the logo follows the theme instead of needing a separate export per ground. Set the colour with <code class=\"tok\">color</code> on <code class=\"tok\">.logo</code>; everything inherits.": "<strong>文字標誌以遮罩繪製，而非固化於圖檔中。</strong>每款組合標誌只需一個檔案，即可呈現黑、白、金三色，標誌因而能跟隨主題，毋須為每種底色另行輸出。在 <code class=\"tok\">.logo</code> 上以 <code class=\"tok\">color</code> 設定顏色，其餘部分自動繼承。",
 "<strong>Always supply vector to a printer.</strong> The mark carries gradients; a rasterised copy bands on press and cannot be trapped. If a supplier asks for a PNG, ask what they intend to do with it.": "<strong>交付印刷商時必須提供向量檔。</strong>標誌帶有漸變，點陣檔上機會出現色階斷層，亦無法做補漏白。若供應商索取 PNG，應先了解其用途。",
 "<strong>Below 1100&nbsp;px</strong> the red block stops being a parallelogram: it becomes a full-width 44&nbsp;px red strip beneath the lockup, with the PolyU logo centred. The slanted edge does not survive at small sizes and should not be faked.": "<strong>寬度低於 1100&nbsp;px 時</strong>，紅色塊不再是平行四邊形：它會變成標誌下方一條 44&nbsp;px 高的通欄紅帶，理大標誌置中。斜邊在小尺寸下無法成立，亦不應勉強模擬。",
 "<strong>Sections alternate ground, not padding.</strong> Every section is 96&nbsp;px top and bottom. Alternate <code class=\"tok\">--paper</code> and <code class=\"tok\">--paper-tint</code>, with an occasional <code class=\"tok\">--ink</code> or <code class=\"tok\">--grad-crimson</code> band. Do not vary section padding to create emphasis.": "<strong>章節以底色交替，而非以間距交替。</strong>每個章節上下留白皆為 96&nbsp;px。以 <code class=\"tok\">--paper</code> 與 <code class=\"tok\">--paper-tint</code> 交替，偶爾插入 <code class=\"tok\">--ink</code> 或 <code class=\"tok\">--grad-crimson</code> 色帶。切勿藉調整章節留白製造強調。",
 "<strong>Display type is Roman, not Thin.</strong> The brand's own cover artwork sets its title in Helvetica Neue Roman, and that is the display setting here too.": "<strong>大字標題用 Roman，不用 Thin。</strong>品牌自身的封面圖檔以 Helvetica Neue Roman 排印標題，本指引的大字設定亦沿用此字重。",
 "<strong>Ink is a rich black, not 100K.</strong> At <code class=\"tok\">#14110E</code> it carries a warm cast that matches the cream stock. Setting it as flat 100K will read cold and thin against Paper; the conversion above keeps the supporting channels.": "<strong>墨色為複合黑，而非單色黑。</strong><code class=\"tok\">#14110E</code> 帶有與米色紙張相配的暖調。若設為單色 100K，在米色底上會顯得冷硬而單薄；上述換算保留了輔助色版。",
 "<strong>Shapes are filled with a gradient, never a flat colour.</strong> Set <code class=\"tok\">--fam-grad</code> to one of the five <code class=\"tok\">--grad-*</code> values. The gradient is what ties the kit to the printed collateral.": "<strong>圖形以漸變填色，絕不用平塗色。</strong>將 <code class=\"tok\">--fam-grad</code> 設為 <code class=\"tok\">--grad-*</code> 其中一個色值。漸變正是把這套組件與印刷物料連繫起來的關鍵。",
 "<strong>Never combine two families in one shape</strong>, and never outline a shape. They are solid fields.": "<strong>切勿在同一圖形中混用兩個色彩家族</strong>，亦切勿為圖形加上外框。它們是實心色塊。",
 "<strong>Never put two ink or two family bands next to each other,</strong> and never open a page with one. A visitor should reach the first dark band having already read something.": "<strong>切勿讓兩條深色帶或兩條家族色帶相鄰</strong>，亦不可以任何一種作為頁面開端。訪客應在讀過一些內容之後，才遇上第一條深色帶。",
 "<strong>Nothing inside a family band may hard-code a text colour.</strong> The band is dark in Light and <em>light</em> in both dark themes, so a literal white becomes unreadable the moment the theme changes. Use <code class=\"tok\">--on-crimson</code>. This is the single most common mistake in this system.": "<strong>家族色帶內的任何元素都不得寫死文字顏色。</strong>該色帶在淺色主題下是深色，在兩款深色主題下卻是<em>淺色</em>，因此一旦切換主題，寫死的白色便無法閱讀。請使用 <code class=\"tok\">--on-crimson</code>。這是本系統中最常見的錯誤。",
 "<strong>At most two shapes on a printed surface, and never more than two families.</strong> On screen a card grid can carry four families because each tile is a separate object. A single printed page is one object, and four families on it reads as decoration rather than as a system.": "<strong>單一印刷版面最多兩個圖形，色彩家族亦不得多於兩個。</strong>螢幕上的卡片網格可承載四個家族，因為每一塊圖磚都是獨立物件；而一張印刷頁面本身就是一個整體，四個家族並置只會被視為裝飾，而非一套系統。",
 "<strong>Metadata text uses <code class=\"tok\">--meta</code>, not PolyU Grey.</strong> <code class=\"tok\">#58595B</code> is tuned to a light ground and falls to 2.5:1 on the dark themes. <code class=\"tok\">--meta</code> is remapped per theme and is what card dates, table headers and the utility row read from.": "<strong>輔助資訊文字使用 <code class=\"tok\">--meta</code>，而非理大灰。</strong><code class=\"tok\">#58595B</code> 是為淺色底調校的，在深色主題下對比度跌至 2.5:1。<code class=\"tok\">--meta</code> 會按主題重新對應，卡片日期、表格標題列及工具列文字均由它取值。",
 "Do": "應做",
 "Don't": "不應做",
 "Never recolour": "絕不改色",
 "Never stretch": "絕不拉伸",
 "Never respace": "絕不改動間距",
 "Never add effects": "絕不加特效",
 "Never set in live type": "絕不以文字排版重製",
 "Never on a busy or family ground": "絕不置於繁雜或家族色底上",
 "Never crowd": "絕不擠迫",
 "Never double the endorsement": "絕不重複署名",
 "Never rebuild the mark": "絕不自行拼砌標誌",
 "Rule": "規則",
 "Screen": "螢幕",
 "Situation": "情況",
 "Use": "採用",
 "Why": "原因",
 "Zone": "區塊",
 "Contains": "內容",
 "Property": "屬性",
 "Token": "變數",
 "Value": "數值",
 "rem": "rem",
 "px": "px",
 "Typical use": "典型用途",
 "PolyU name": "理大字重名稱",
 "CSS": "CSS",
 "Min → Max": "最小 → 最大",
 "Weight": "字重",
 "Line height": "行高",
 "Role": "用途",
 "Name": "名稱",
 "HEX": "HEX",
 "RGB": "RGB",
 "CMYK": "CMYK",
 "Status": "狀態",
 "Family": "色彩家族",
 "One ink + tint ramp": "單一油墨 + 網點漸變",
 "ΔE₀₀ at the light end": "淺端的 ΔE₀₀",
 "Verdict": "結論",
 "Shape": "圖形",
 "Class": "類別名稱",
 "Geometry": "幾何構成",
 "Where it is used": "應用場合",
 "Ground": "底色",
 "Frequency": "使用頻率",
 "Text colour comes from": "文字顏色來源",
 "Setting": "設定",
 "Artifact": "物料",
 "Size": "尺寸",
 "Notes": "備註",
 "Dark, stop 1": "深色，端點 1",
 "Dark, stop 2": "深色，端點 2",
 "<strong>Unit lockup.</strong> The standalone logo. The only zone that differs between PolyU sites.": "<strong>單位標誌。</strong>獨立式組合標誌。這是各理大網站之間唯一有分別的區塊。",
 "<strong>Parent unit.</strong> The College of Undergraduate Studies logo, in the slot a departmental site gives its Faculty.": "<strong>上級單位。</strong>本科生院標誌，位置相當於學系網站放置學院標誌之處。",
 "<strong>PolyU block.</strong> Fixed University furniture. Never recoloured, never carrying BDSIS artwork.": "<strong>理大色塊。</strong>大學的既定元素。絕不改色，亦絕不置入 BDSIS 圖像。",
 "Wrong order. The University logo always leads.": "次序錯誤。大學標誌必須置前。",
 "Full colour on a warm uncoated stock. The mark's gradients hold on uncoated paper because the families are mid-tone.": "暖調非塗佈紙上的全彩版本。由於色彩家族屬中間調，標誌的漸變在非塗佈紙上仍能保持。",
 "Full colour on a mid-tone or coloured stock. The mark loses separation and the wordmark loses contrast.": "中間調或有色紙張上的全彩版本。標誌各區塊失去分辨度，文字標誌亦失去對比。",
 "One-colour jobs use the monocolor lockup, where the quadrant gaps carry the construction.": "單色印件採用單色組合標誌，各區塊之間的空隙負責呈現其構成。",
 "Never desaturate the full-colour mark to make a one-colour version. The quadrants collapse to near-identical greys.": "切勿將全彩標誌去飽和以製作單色版本。各區塊會塌縮成幾乎相同的灰階。",
 "Never box the logo in a white patch to force it onto a coloured ground.": "切勿為標誌加上白色方框，藉此強行置於有色底上。",
 "Shape marker, heading in ink at Medium. It holds against the cream.": "圖形標記，標題以 Medium 字重的墨色排印，在米色底上穩得住。",
 "Thin weight in PolyU Red. The red belongs to the banner, and Thin dissolves at this size.": "以理大紅配 Thin 字重。該紅色屬於橫幅，而 Thin 在此字級下會化開。",
 "Hard-coded white on Tangerine measures 2.1:1 and fails AA. Same for Olive at 2.2:1 and Ocean at 3.7:1.": "橘色上寫死白字實測 2.1:1，未達 AA 標準。橄欖綠 2.2:1、海洋藍 3.7:1，同樣不合格。",
 "One quarter-round on the bottom-right, or none at all.": "右下角一個四分之一圓角，或完全不設圓角。",
 "Four soft corners, or a pill. Neither exists in the mark.": "四角皆圓，或膠囊形。兩者都不存在於標誌之中。",
 "Solid, filled with a family gradient.": "實心，並以家族漸變填色。",
 "Outlined, flat-filled, and a fourth shape that is not in the kit.": "加了外框、用了平塗色，還多出一個不屬於組件的第四種圖形。",
 "Let a measure do the wrapping. It survives whichever face loads.": "讓行長決定斷行位置。無論載入哪款字體都能成立。",
 "Hard breaks tuned in Helvetica Neue. Shown here in Arial, which is what Windows and Android actually get.": "依 Helvetica Neue 調校的硬斷行。此處以 Arial 呈現，即 Windows 與 Android 使用者實際看到的效果。",
 "Rotate the motif and the family down the row.": "沿整列輪換圖形母題與色彩家族。",
 "The same tile three times reads as wallpaper, not as three stories.": "同一塊圖磚重複三次，看來像牆紙，而非三則消息。",
 "<strong>Photograph the actual cohort, mentors and campus.</strong> The programme's proposition is one-on-one attention from named professors; stock models contradict it.": "<strong>拍攝真實的學生、導師與校園。</strong>本課程的賣點是由具名教授一對一指導；使用素材庫模特兒與此自相矛盾。",
 "<strong>Never crop a face into a rounded corner.</strong> If a portrait needs a container, keep it square.": "<strong>切勿將人臉裁入圓角。</strong>若人像需要容器，請保持直角。",
 "<strong>16:10 for cards, 3:2 for portraits, full-bleed for hero.</strong>": "<strong>卡片 16:10，人像 3:2，首屏滿版出血。</strong>",
 "<strong>No colour overlays on photographs.</strong> The spectrum lives in the cell tiles; tinting a photo red makes it look like a different institution's brand.": "<strong>相片上不加色彩疊層。</strong>色彩由色塊圖磚承載；為相片鋪上紅色調，只會令它看似另一所機構的品牌。",
 "Where no photograph exists, use a cell tile.": "沒有可用相片時，改用色塊圖磚。",
 "<strong>Focus.</strong> A 3&nbsp;px <code class=\"tok\">--is-blue-ink</code> outline at 2&nbsp;px offset, on every interactive element. Never remove it.": "<strong>焦點框。</strong>所有互動元素均有 3&nbsp;px 的 <code class=\"tok\">--is-blue-ink</code> 外框，偏移 2&nbsp;px。絕不可移除。",
 "<strong>Keyboard.</strong> Drop panels open on <code class=\"tok\">:focus-within</code> as well as hover, so the navigation works without a mouse.": "<strong>鍵盤操作。</strong>下拉面板除滑過外亦可由鍵盤焦點開啟，因此不使用滑鼠亦能瀏覽。",
 "<strong>Skip link.</strong> First element in the DOM, visible on focus.": "<strong>跳過連結。</strong>置於 DOM 最前，獲得焦點時顯示。",
 "<strong>Carousel.</strong> Must have a visible pause control, must pause on hover, and must not auto-advance under <code class=\"tok\">prefers-reduced-motion</code>.": "<strong>輪播。</strong>必須設有可見的暫停控制項，滑鼠移入時暫停，並在 <code class=\"tok\">prefers-reduced-motion</code> 下停止自動播放。",
 "<strong>Language.</strong> Chinese passages inside an English page need <code class=\"tok\">lang=\"zh-Hant\"</code> so screen readers switch voice.": "<strong>語言標記。</strong>英文頁面中的中文段落須加上 <code class=\"tok\">lang=\"zh-Hant\"</code>，讀屏軟件方能切換語音。",
 "12 columns · 24&nbsp;px gutters · 1280&nbsp;px container": "十二欄 · 欄距 24&nbsp;px · 容器 1280&nbsp;px",
 "An 8&nbsp;px base with a 4&nbsp;px half-step. Every margin, padding and gap on the site is one of these nine values. Nothing else is permitted.": "以 8&nbsp;px 為基數，另設 4&nbsp;px 半階。網站上每一處外距、內距與間隙皆取自這九個數值，不容其他數值。",
 "An 8&nbsp;px base with a 4&nbsp;px half-step. Every margin, padding and gap on the site is one of these nine values, drawn here at true width.": "以 8&nbsp;px 為基數，另設 4&nbsp;px 半階。網站上每一處外距、內距與間隙皆取自這九個數值，此處按實際寬度繪製。",
 "Icon nudges, chip padding": "圖示微調、標籤內距",
 "List item gaps, inline gaps": "列表項間距、行內間距",
 "Label to heading": "標籤至標題",
 "Paragraph spacing, heading to body": "段落間距、標題至正文",
 "Grid gaps, card padding, gutters": "網格間隙、卡片內距、欄距",
 "Group separation": "組別分隔",
 "Section head to content": "章節標題至內容",
 "Tight section padding": "緊湊章節留白",
 "Standard section padding": "標準章節留白",
 "4px · icon nudges": "4px · 圖示微調",
 "8px · inline gaps": "8px · 行內間距",
 "12px · label to heading": "12px · 標籤至標題",
 "16px · paragraphs": "16px · 段落",
 "24px · gutters, card padding": "24px · 欄距、卡片內距",
 "32px · group separation": "32px · 組別分隔",
 "48px · head to content": "48px · 標題至內容",
 "64px · tight sections": "64px · 緊湊章節",
 "96px · standard sections": "96px · 標準章節",
 "--maxw · 1280px content container": "--maxw · 1280px 內容容器",
 "--maxw-narrow · 840px long-form measure": "--maxw-narrow · 840px 長文行寬",
 "68ch · the hard cap on every paragraph": "68ch · 所有段落的硬上限",
 "Copy this into any BDSIS web project.": "可直接複製到任何 BDSIS 網頁專案中。",
 "Do not build a hamburger drawer duplicating the panel contents; the two versions drift apart.": "切勿另建與面板內容重複的漢堡選單；兩個版本終將各自演變、內容不一。",
 "<strong>Contrast.</strong> Body text at 4.5:1 minimum, large text at 3:1. Measured on the cream ground: <code class=\"tok\">--ink</code> 16.9:1, <code class=\"tok\">--ink-body</code> 9.3:1, <code class=\"tok\">--ink-muted</code> 5.1:1, BDSIS Red 6.7:1. The four family colours are <em>not</em> text-safe — see §07.": "<strong>對比度。</strong>正文最低 4.5:1，大字最低 3:1。於米色底上實測：<code class=\"tok\">--ink</code> 16.9:1、<code class=\"tok\">--ink-body</code> 9.3:1、<code class=\"tok\">--ink-muted</code> 5.1:1、BDSIS 紅 6.7:1。四個色彩家族<em>不可</em>作文字使用——見 §07。",
 "Each token drawn at the value it actually holds.": "每個變數均以其實際數值繪製。",
 "<strong>Helvetica does the talking.</strong> PolyU's official English typeface is Helvetica, and there is no second display face on the web. Hierarchy comes from weight, size and space. Never from a decorative font. Headings sit in the warm black, Roman at display and h1, Medium from h2 down.": "<strong>由 Helvetica 說話。</strong>理大的官方英文字體是 Helvetica；網上並無第二款標題字體。層次來自字重、字級與留白，絕不倚靠裝飾性字體。標題採用暖黑色——大字及 h1 用 Roman，h2 以下用 Medium。",
 "<strong>Draw with the shape kit, not with decoration.</strong> There are four primitives, one per colour family: a quarter circle in two orientations, a square, a triangle and a circle. Between them they do all the graphic work, from section markers to tiles, avatars and the hero opener. A container is either square-cornered or carries one quarter-round. A box with four soft corners belongs to no shape in the kit.": "<strong>以圖形組件作圖，而非以裝飾作圖。</strong>四個基本圖形——兩個方向的四分圓、方形、三角形與圓形——各對應一個色彩家族，承擔全部圖像工作：章節標記、圖磚、頭像、首屏開端。容器要麼是直角，要麼帶一個四分之一圓角。四角皆圓的方框並不屬於這套組件。",
 "Colour and shape combine to form the PolyU Interdisciplinary Studies logomark. It is fixed artwork, never redrawn, respaced or recoloured. Everything else in this document comes out of it. The shape kit in §08 is its geometry, and the families in §07 are its palette.": "色彩與圖形結合，構成 PolyU Interdisciplinary Studies 的標誌。標誌為既定圖檔，不得重繪、改動間距或改色。本文件其餘內容皆源自於此：§08 的圖形組件取自它的幾何構成，§07 的色彩家族取自它的用色。",
 "Two grounds and two colourways. The University logo reversed on red, beside a full-colour programme logo on white, reads as a seam rather than a lockup.": "兩種底色、兩種色版。大學標誌反白於紅底，旁邊卻是白底上的全彩課程標誌——並置起來像是一道接縫，而非一組標誌。",
 "On a family field such as a booth wall, a roll-up or a folder, reverse the monocolor lockup out in white.": "在家族色塊上——展位牆身、易拉架、文件夾——應將單色組合標誌反白使用。",
 "The banner is University furniture, and it runs white across polyu.edu.hk. On the dark themes it takes the theme's surface rather than staying literally white. The PolyU block still keeps its red, and the College logo is knocked through instead of sitting in a white box. Nothing else in the bar changes.": "橫幅屬於大學的既定元素，在 polyu.edu.hk 各處均為淺色。在深色主題下，它採用該主題的表面色而非維持純白——但理大色塊保留紅色，學院標誌則以去底方式呈現，不會置於白色方框內。橫幅其餘部分一概不變。",
 "One row, sticky, six to eight top-level items, sentence case. Items are set at 17&nbsp;px Roman in <code class=\"tok\">--ink-body</code>. The active and hovered state uses <code class=\"tok\">--is-crimson-ink</code>, our own red, which each theme relights, with a 3&nbsp;px underline. Drop panels carry a 3&nbsp;px red top edge and list at 15&nbsp;px.": "單行、置頂固定，六至八個第一層項目，採用句首大寫。項目字級 17&nbsp;px Roman，顏色為 <code class=\"tok\">--ink-body</code>；選中及滑過狀態為 <code class=\"tok\">--is-crimson-ink</code>（我們的紅色，各主題會重新調校），並加上 3&nbsp;px 底線。下拉面板頂部有 3&nbsp;px 紅色邊，項目字級 15&nbsp;px。",
 "<strong>Panel visibility is owned by <code class=\"tok\">web.js</code>, not by CSS <code class=\"tok\">:hover</code>.</strong> Pure CSS left a panel stuck open. Clicking a nav link parks focus inside it, so <code class=\"tok\">:focus-within</code> held the panel there and a second one could open alongside. The script guarantees exactly one panel is open. It adds a 140&nbsp;ms grace period so a diagonal mouse path to the panel does not snap it shut, opens on <code class=\"tok\">:focus-visible</code> for keyboard users, and closes on Escape or an outside click.": "<strong>面板的開合由 <code class=\"tok\">web.js</code> 控制，而非 CSS 的 <code class=\"tok\">:hover</code>。</strong>純 CSS 會令面板卡住不關——點擊導覽連結後焦點停留其中，<code class=\"tok\">:focus-within</code> 便一直保持開啟，甚至可能同時開啟第二個面板。此腳本確保任何時候只有一個面板開啟，並加入 140&nbsp;ms 緩衝，使滑鼠斜向移往面板時不會突然關閉；鍵盤使用者以 <code class=\"tok\">:focus-visible</code> 開啟，按 Escape 或點擊外部即關閉。",
 "A 12-column grid inside a 1280&nbsp;px container, with 24&nbsp;px gutters. Long-form reading drops to an 840&nbsp;px measure. Body copy is capped at <strong>68 characters</strong> regardless of container width. That cap is set globally on <code class=\"tok\">p</code> and should not be overridden.": "1280&nbsp;px 容器內的十二欄網格，欄距 24&nbsp;px。長文閱讀寬度收窄至 840&nbsp;px。無論容器多寬，正文行長上限為 <strong>68 個字元</strong>——此設定在 <code class=\"tok\">p</code> 上全域生效，不應覆寫。",
 "<strong>Helvetica is PolyU's official English typeface.</strong> Helvetica Neue is the cut the University specifies, in five weights: Thin, Light, Roman, Medium and Bold. MHei is the official Chinese typeface. For online use the University also sanctions <strong>Roboto</strong> and <strong>Heiti</strong> as secondary faces. Written as CSS, that policy is the whole font stack:": "<strong>Helvetica 是理大的官方英文字體</strong>，大學指定的字型為 Helvetica Neue，包括 Thin、Light、Roman、Medium 及 Bold 五種字重。中文官方字體為 MHei。網上應用方面，大學另外認可 <strong>Roboto</strong> 及 <strong>Heiti</strong> 作為次要字體。以下字體堆疊即為此政策的 CSS 寫法：",
 "Helvetica Neue is a <em>system</em> font on Apple devices, not a licensed webfont. Roughly half your visitors, on Windows and Android, will see <strong>Roboto or Arial</strong> instead. Both are narrower than Helvetica Neue at the same size, so a headline set to fill a line on a Mac will break early or leave a gap elsewhere.": "Helvetica Neue 在 Apple 裝置上是<em>系統</em>字體，並非已授權的網頁字體。約有一半訪客——Windows 與 Android 使用者——看到的會是 <strong>Roboto 或 Arial</strong>。兩者在相同字級下均較 Helvetica Neue 窄，因此在 Mac 上剛好填滿一行的標題，在其他裝置上會提早斷行或留下空隙。",
 "Two consequences follow, and both are mandatory. <strong>One:</strong> check every headline in Arial before it ships, and never hard-code a line break that only works in one face. <strong>Two:</strong> if pixel-identical rendering matters, the University will need to license the Helvetica Neue webfont from Monotype and self-host it. Until that happens, Roboto is the sanctioned and expected fallback, and designs have to look deliberate in it.": "由此衍生兩項必須遵守的要求。<strong>其一：</strong>所有標題在發佈前須以 Arial 檢視，切勿寫死只在單一字體下成立的斷行。<strong>其二：</strong>若必須確保逐像素一致的呈現，大學須向 Monotype 授權 Helvetica Neue 網頁字體並自行託管；在此之前，Roboto 是獲認可且可預期的替代字體，設計在該字體下亦須顯得有意為之。",
 "Taken from the PolyU Brand Communication Guidelines. These are not adjustable, and on a BDSIS site PolyU Red appears in exactly one place: the banner block behind the University logo.": "取自《理大品牌傳訊指引》。這些色值不可調整；在 BDSIS 網站上，理大紅只出現於一處——橫幅中大學標誌背後的色塊。",
 "<strong>One family takes white text; three do not.</strong> This is measured rather than assumed. White on Red is 7.5:1. White on Tangerine is <strong>2.1:1</strong>, on Olive <strong>2.2:1</strong> and on Ocean <strong>3.7:1</strong>, so all three fail. Put <code class=\"tok\">--ink</code> on those instead, where they measure 8.8:1, 8.4:1 and 7.1:1. The component API for this is <code class=\"tok\">--on-fam</code>.": "<strong>只有一個家族可承載白字，其餘三個不可。</strong>這是實測結果，並非推測。白字於紅色上為 7.5:1；於橘色上僅 <strong>2.1:1</strong>、橄欖綠上 <strong>2.2:1</strong>、海洋藍上 <strong>3.7:1</strong>——三者皆不合格。這三個家族應改用 <code class=\"tok\">--ink</code>，實測分別為 8.8:1、8.4:1 及 7.1:1。對應的元件變數為 <code class=\"tok\">--on-fam</code>。",
 "Tangerine's two stops are not a light and a dark version of one colour. <code class=\"tok\">#F2A03B</code> is an amber and <code class=\"tok\">#E14729</code> is a vermilion, roughly 40° apart in hue. No amount of screening turns one into the other, and the best single-ink attempt lands at ΔE 21, which is a different colour rather than a near miss.": "橘色的兩個漸變端點並非同一顏色的深淺版本——<code class=\"tok\">#F2A03B</code> 是琥珀色，<code class=\"tok\">#E14729</code> 是朱紅色，色相相距約 40°。無論如何加網都無法由其一變成其二；單一油墨的最佳嘗試為 ΔE 21，這並非些微偏差，而是另一種顏色。",
 "There are two options. <strong>Either</strong> run it as two inks, PMS 1375 C into PMS 7578 C, which is the only way to keep the gradient and costs a second plate. <strong>Or</strong> accept a flat Tangerine in spot work and use PMS 1375 C alone. For most jobs the second is the right call, since Tangerine appears on the smallest surfaces in the system and a flat field there is no loss.": "有兩個選擇。<strong>其一</strong>，以兩種油墨印製，由 PMS 1375 C 漸變至 PMS 7578 C，這是保留漸變的唯一方法，但需增加一塊印版。<strong>其二</strong>，在專色印刷中接受平塗的橘色，單用 PMS 1375 C。多數情況下第二個選擇較合理：橘色在本系統中只出現於最小的版面，平塗並無損失。",
 "<strong>None of these is official until someone looks at a printed proof.</strong> The ΔE figures above are computed against widely published sRGB approximations of each Pantone rather than against Pantone's own spectral measurements, and spot inks sit partly outside sRGB. The numbers rank candidates well but cannot confirm one. Order a draw-down, or check against a current Pantone Formula Guide under D50 lighting, then record the confirmed numbers here and treat <em>those</em> as the authority.": "<strong>在有人親眼核對印稿之前，以上色號一概未經確認。</strong>上述 ΔE 數值是以各 Pantone 色廣泛流通的 sRGB 近似值計算，並非 Pantone 自身的光譜實測值，而專色油墨部分落在 sRGB 色域之外——因此這些數值足以為候選色排序，卻無法確認任何一個。請索取印墨試色樣，或在 D50 光源下對照最新的 Pantone 色彩指南，再將確認後的色號記錄於此，並以<em>該等色號</em>為準。",
 "<strong>Default to process CMYK.</strong> The artwork was drawn for it, gradients work in it, and the families were never designed as spot colours. Reach for Pantone only where process is not available, on signage, foil, embroidery or single-colour merchandise, or where a run is long enough that a spot plate is cheaper than four.": "<strong>以四色印刷為預設。</strong>圖檔本為此而繪，漸變在四色下可行，而色彩家族從來不是按專色設計。只有在四色不可行時才採用 Pantone——例如標識牌、燙金、刺繡、單色紀念品——或印量大至一塊專色版比四塊版更划算的情況。",
 "<strong>CMYK in this table is a conversion, not a measurement.</strong> It is a standard GCR conversion from the hex values, adequate for a first proof and for office printing. Before a production run, send the printer the HEX and RGB values and let them output through their own ICC profile. A coated stock and an uncoated stock will not give the same numbers, and Tangerine in particular sits close to the edge of CMYK gamut, so it will print duller than it appears on screen.": "<strong>此表中的 CMYK 為換算值，並非實測值。</strong>它由十六進位色值以標準 GCR 方式換算，足以應付初步打樣及辦公室列印。正式付印前，請將 HEX/RGB 色值交予印刷商，並以其自身的 ICC 色彩描述檔輸出——粉紙與非塗佈紙不會得出相同數值，其中橘色尤其接近 CMYK 色域邊緣，印出效果會較螢幕上暗淡。",
 "<strong>Do not print the Paper colour as a flood tint.</strong> <code class=\"tok\">#F8F2E7</code> exists because a screen is white by default and paper is not. Choose a warm uncoated stock instead. A flood tint costs ink, shows every roller mark, and still looks flatter than the stock would.": "<strong>切勿以滿版底色印製米色。</strong><code class=\"tok\">#F8F2E7</code> 之所以存在，是因為螢幕預設為白色而紙張並非如此。請改為選用暖調的非塗佈紙——滿版底色耗墨、會顯露每一道輥痕，效果仍不及紙張本身自然。",
 "<strong>Contrast.</strong> Body text at 4.5:1 minimum, large text at 3:1. Measured on the cream ground, <code class=\"tok\">--ink</code> gives 16.9:1, <code class=\"tok\">--ink-body</code> 9.3:1, <code class=\"tok\">--ink-muted</code> 5.1:1 and BDSIS Red 6.7:1. The four family colours are <em>not</em> text-safe, as set out in §07.": "<strong>對比度。</strong>正文最低 4.5:1，大字最低 3:1。於米色底上實測：<code class=\"tok\">--ink</code> 16.9:1、<code class=\"tok\">--ink-body</code> 9.3:1、<code class=\"tok\">--ink-muted</code> 5.1:1、BDSIS 紅 6.7:1。四個色彩家族<em>不可</em>作文字使用——見 §07。",
 "<strong>Motion.</strong> All transitions 180–250&nbsp;ms on <code class=\"tok\">--ease</code>. Everything collapses to 0.01&nbsp;ms under reduced motion. That is handled globally, so do not write bespoke animation that bypasses it.": "<strong>動效。</strong>所有轉場為 180–250&nbsp;ms，緩動曲線為 <code class=\"tok\">--ease</code>。在減少動態偏好下一律縮至 0.01&nbsp;ms——此設定為全域生效，切勿另寫繞過它的動畫。",
 "<code class=\"tok\">--on-orange</code> on Tangerine measures 8.8:1 in Light, and stays right when the theme changes. A hard-coded ink would not.": "橘色上使用 <code class=\"tok\">--on-orange</code>，在淺色主題下實測 8.8:1，且切換主題後依然正確——寫死的墨色則不然。",
 "<strong>The PolyU block keeps its red in every theme.</strong> The University mark is never recoloured or knocked back, whatever the ground behind it. The College logo is supplied as artwork on a white field, so on the dark themes it is knocked through with <code class=\"tok\">invert(1) hue-rotate(180deg)</code>. The rotation puts the PolyU red back where the inversion took it.": "<strong>理大色塊在所有主題中維持紅色。</strong>無論背後底色為何，大學標誌絕不改色或減淡。學院標誌的原始圖檔帶白色底，因此在深色主題下以 <code class=\"tok\">invert(1) hue-rotate(180deg)</code> 去底——色相旋轉可把反相後偏移的理大紅還原。",
 "<strong>Dark Mono Gold is a register, not a dark mode.</strong> Reserve it for material with an occasion attached, such as awards, the annual review and invitations. Not the prospectus.": "<strong>深色單金是一種語調，而非深色模式。</strong>只保留予具儀式性的物料——獎項、年度報告、邀請函，而非招生簡介。",
 "BDSIS sits inside the University, so its web pages inherit PolyU's institutional furniture: the banner, the red, the grey and Helvetica. To that they add two things of their own, a warm cream ground and a kit of shapes drawn from the programme artwork. This document specifies both, and every rule in it describes <code class=\"tok\">web.css</code>, the stylesheet that <a href=\"index.html\">the site itself</a> runs on.": "BDSIS 隸屬於大學，因此其網頁沿用理大的機構元素——橫幅、紅色、灰色與 Helvetica——並加入兩項專屬元素：溫暖的米色底色，以及取自課程圖檔的一套圖形組件。本文件同時規範兩者，而當中每一條規則所描述的都是 <code class=\"tok\">web.css</code>，即<a href=\"index.html\">網站本身</a>所採用的樣式表。",
 "<strong>Utilities.</strong> Search, share, Intranet and Quick Access, right-aligned and always clear of the red block.": "<strong>工具列。</strong>搜尋、分享、內聯網、快速連結——靠右對齊，並須始終避開紅色塊。",
 "60 credits · Flexible Major": "60 學分 — 彈性主修",
 "A tailor-made study of a major local, national or global issue, such as a UNESCO Sustainable Development Goal. Subjects are selected from any department, and may include a few from other universities.": "圍繞一項重大的本地、國家或全球議題度身設計，例如聯合國教科文組織的可持續發展目標。科目可選自任何部門，亦可包括少量其他大學的科目。",
 "Judgement rests on wisdom, experience and maturity. Those in turn rest on a deep understanding of human behaviour, needs and aspirations, and of how societies form and hold together.": "判斷力源自智慧、經驗與成熟，而這些又建基於對人類行為、需求與抱負的深刻理解，以及對社會如何形成與維繫的洞察。",
 "Three things, one stylesheet": "三者合一，共用一套樣式表",
 "A site, the rules it was built from, and the printed pieces those rules produce. All three run on <code class=\"tok\">web.css</code>, so the specification can never drift from the thing it specifies.": "網站、建構網站所依據的規範，以及依規範製作的印刷品。三者同樣以 <code class=\"tok\">web.css</code> 運行，規範與成品永不脫節。",
 "The sample website": "網站示例",
 "The brand guidelines": "品牌指引",
 "The print artifacts": "印刷品",
 "A departmental site for the scheme, built to the guidelines. Content is faked from the programme slides.": "依品牌指引建構的課程網站，內容取自課程簡報，僅作示例。",
 "Fifteen sections covering the logo, colour, typography, the shape kit and print. Every specimen is the live component.": "十五個章節，涵蓋標誌、色彩、字體、圖形組件與印刷。每個示例均為實際組件。",
 "Letterhead, business card, ID card, luggage tag and display board, drawn at true proportion and exportable as vector PDF.": "信紙、卡片、學生證、行李牌與展板，均按實際比例繪製，可匯出向量 PDF。",
 "Open the site →": "瀏覽網站 →",
 "Read the guidelines →": "閱讀品牌指引 →",
 "See the artifacts →": "查看印刷品 →",
 "Sample website": "網站示例",
 "Print artifacts": "印刷品",
 "BDSIS Brand System · Copyright © 2026 The Hong Kong Polytechnic University.": "跨學科學士學位組合課程品牌系統 · 版權所有 © 2026 香港理工大學",
});
